include(joinpath(@__DIR__(), "test_suite.jl"))

basic_smoketest()
neuron_and_neural_mass_comparison_tests()
basic_hh_network_tests()
stochastic_hh_network_tests()
ngei_test()
kuramato_test()
wta_tests()
dbs_circuit_components()
dbs_circuit()
discrete()
striatum_tests()
lif_exci_inh_tests()
decision_making_test()
