name: 'Create Update PR'
description: 'Checks for changes and creates a PR with updates if changes exist'
inputs:
  commit-message:
    description: 'Commit message for the changes'
    required: false
    default: 'Update generated files from CI'
  pr-title-prefix:
    description: 'Prefix for the PR title'
    required: false
    default: 'Update reference files'
  pr-body:
    description: 'Body content for the PR'
    required: false
    default: 'This PR updates files generated during CI.'
  branch-prefix:
    description: 'Prefix for the update branch name'
    required: false
    default: 'update-files'
  github-token:
    description: 'GitHub token for creating PRs'
    required: true
  reference-path:
    description: 'Path where reference test files'
    required: true
  reference-staging-path:
    description: 'Staging path where updated reference test files go'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Validate Reference Path is within the Repository
      shell: bash
      run: |
        if ! git rev-parse --is-inside-work-tree --quiet "${{ inputs.reference-path }}" > /dev/null; then
          echo "Error: Argument reference-path '${{ inputs.reference-path }}' is outside of the Git repository's working directory. Aborting."
          exit 1
        fi
        
        if [[ "${{ inputs.reference-staging-path }}" == /* || "${{ inputs.reference-staging-path }}" == *"../"* ]]; then
          echo "Error: reference-staging-path '${{ inputs.reference-staging-path }}' contains absolute path components or parent directory traversal."
          exit 1
        fi
    - name: Check for changes
      id: check_changes
      shell: bash
      continue-on-error: true
      run: |
        echo "Reference path ${{ inputs.reference-path }} Staging path ${{ inputs.reference-staging-path }}"
        mv ${{ inputs.reference-staging-path }}** ${{ inputs.reference-path }}
        git diff --quiet --exit-code ${{ inputs.reference-path }} || echo "has_changes=true" >> $GITHUB_OUTPUT
    - name: Check for changes debug
      shell: bash
      continue-on-error: true
      run: |
        echo " has changes: ${{ steps.check_changes.outputs.has_changes }}"
    - uses: sersoft-gmbh/setup-gh-cli-action@v3
    - name: Create PR with updates
      if: always() && steps.check_changes.outputs.has_changes == 'true'
      shell: bash
      continue-on-error: true
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        # Configure git
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Create a new branch for the updates
        UPDATE_BRANCH="${{ inputs.branch-prefix }}-${{ github.head_ref }}-${{ github.run_number }}"
        git checkout -b "$UPDATE_BRANCH"
        
        # Commit the changes
        
        git add ${{ inputs.reference-path }}
        git commit -m "${{ inputs.commit-message }}
        
        Auto-generated by CI run #${{ github.run_number }}
        Original PR: #${{ github.event.pull_request.number }}"
        
        # Push the new branch
        git push origin "$UPDATE_BRANCH"
        
        # Create PR targeting the original PR's branch
        gh pr create \
          --base "${{ github.head_ref }}" \
          --head "$UPDATE_BRANCH" \
          --title "${{ inputs.pr-title-prefix }} for PR #${{ github.event.pull_request.number }}" \
          --body "${{ inputs.pr-body }}
        
        Original PR: #${{ github.event.pull_request.number }}
        
        ## Instructions
        Carefully review the changes and **only** merge this PR into \`${{ github.head_ref }}\` if you agree these updates are appropriate.
        
        ---
        Auto-generated by [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
