name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - group: Basics
            flag: 'O1'
            version: '1'
          - group: Advanced
            flag: 'O1'
            version: '1'
          - group: Small_CS_RL_Pipeline
            flag: 'O3'
            version: '1'
          - group: GraphDynamics1
            flag: 'O1'
            version: '1'
          - group: GraphDynamics2
            flag: 'O1'
            version: '1'
          - group: GraphDynamics3
            flag: 'O1'
            version: '1'
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - name: Run tests
        run: julia --project=. -e 'using Pkg; Pkg.test("Neuroblox"; julia_args=["-O1"])'
        env:
          JULIA_NUM_THREADS: 4
          GROUP: ${{ matrix.group }}
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v3
        with:
          file: lcov.info
